#SPDX-License-Identifier: MIT-0
---
security_ssh_port: 22

security_ssh_permit_root_login: "no"
security_ssh_pubkey_authentication: true
security_ssh_password_authentication: false
security_ssh_kbd_interactive_authentication: false

security_ssh_x11_forwarding: false
security_ssh_allow_agent_forwarding: false
security_ssh_allow_tcp_forwarding: true
security_ssh_permit_tunnel: false

security_ssh_max_auth_tries: 3
security_ssh_login_grace_time: 30
security_ssh_client_alive_interval: 300
security_ssh_client_alive_count_max: 2

security_ssh_allowed_users: []

security_firewall_manage_forward_chain: false
security_firewall_additional_tcp_ports: []
security_firewall_udp_ports: []