name: Check blog validity

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      
      - name: Setup Node
        uses: actions/setup-node@v7

      - name: npm ci
        working-directory: ./shkillers-site
        run: npm ci
      
      - name: Build website
        working-directory: ./shkillers-site
        run: npm run build

      - name: upload website
        uses: actions/upload-artifact@v7
        with:
          name: shkillers-site
          path: shkillers-site/dist/
          if-no-files-found: error
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download website artufact
        uses: actions/download-artifact@v4
        with:
          name: shkillers-site
          path: shkillers-site/dist
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "${{ secrets.DEPLOY_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Install Ansible
        run: |
          python -m pip install ansible
          ansible-galaxy collection install \
            -r shkillers-infra/collections/requirements.yml

      - name: Create Ansible inventory
        run: |
          cat > shkillers-infra/inventory/production.yml <<EOF
          all:
            children:
              webservers:
                hosts:
                  shkillers:
                    ansible_host: ${{ secrets.DEPLOY_HOST }}
                    ansible_user: ${{ secrets.DEPLOY_USER }}
          EOF
      
      - name: Create vault password file
        working-directory: ./shkillers-infra
        run: |
          printf '%s' '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > .vault-pass
          chmod 600 .vault-pass

      - name: Deploy website
        working-directory: ./shkillers-infra
        run: |
          ansible-playbook \
          -i inventory/production.yml \
          playbooks/provision.yml \
          --tags nginx \
          --vault-password-file /.vault-pass